{
 "title": "Database Assistant",
 "tags": [
  "database",
  "sql",
  "postgresql",
  "monitor",
  "SLDC",
  "delhi",
  "electricity",
  "electricity grid"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL Table Name, Size & Row Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    TRIM('\"' FROM x2[1]) AS \"Table Name\",\n    pg_total_relation_size(TRIM('\"' FROM x2[1])) AS \"Table Size\",\n    CAST(TRIM('\"' FROM x2[2]) AS INTEGER) AS \"Row Count\",\n    NOW() AS \"time\"\nFROM\n    (\n        SELECT\n            STRING_TO_ARRAY(X1, ',') AS X2\n        FROM\n            (\n                SELECT\n                    UNNEST(public.\"get__tableName_rowCount\"()) X1\n            ) AS subquery1\n    ) AS subquery2"
    }
   ]
  },
  {
   "title": "PostgreSQL Table Name & Size",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    CONCAT(table_schema, '.', table_name) AS \"Table Name\",\n    pg_total_relation_size(CONCAT(table_schema, '.', table_name)) AS \"Table Size\"\nFROM\n    information_schema.tables\nWHERE\n    table_schema IN ('public', 'edata', 'metadata') AND\n    table_type = 'BASE TABLE'\nORDER BY \"Table Size\" DESC;"
    }
   ]
  },
  { "title": "Flyway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Schema Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  version\nFROM\n  version_schema\n"
    }
   ]
  },
  {
   "title": "Migration Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  version\nFROM\n  flyway_schema_history\nORDER BY installed_rank DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Migration Installed Rank",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  installed_rank\nFROM\n  flyway_schema_history\nORDER BY installed_rank DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Schema Installation Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 7 },
   "format": "dateTimeAsIso",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  installed_on\nFROM\n  flyway_schema_history\nORDER BY installed_rank DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Flyway Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM flyway_schema_history;"
    }
   ]
  },
  { "title": "Contents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PostgreSQL Table Name, Row Count & Min-Max Serial Number",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n    TRIM('\"' FROM x2[1]) AS \"Table Name\",\n    CAST(TRIM('\"' FROM x2[2]) AS INTEGER) AS \"Row Count\",\n    CAST(TRIM('\"' FROM x2[3]) AS INTEGER) AS \"Minimum\",\n    CAST(TRIM('\"' FROM x2[4]) AS INTEGER) AS \"Maximum\",\n    NOW() AS \"time\"\nFROM\n    (\n        SELECT\n            STRING_TO_ARRAY(X1, ',') AS X2\n        FROM\n            (\n                SELECT\n                    UNNEST(public.\"get__tableName_rowMinMax\"()) X1\n            ) AS subquery1\n    ) AS subquery2"
    }
   ]
  }
 ]
}